; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Expand application partition to ~3MB
board_build.partitions = huge_app.csv

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    fastled/FastLED @ ^3.6.0
    mathertel/RotaryEncoder @ ^1.5.3
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    https://github.com/pschatzmann/ESP32-A2DP.git

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    ; Optimize for size
    -Os
    -I lib/arduino-audio-tools/src